import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService, Member, Plan, Subscription } from './services';
import { CommonModule } from '@angular/common';

@Component({selector:'app-members',standalone:true,imports:[CommonModule, FormsModule],template:`
<div class="top"><div><h1>Članovi</h1><p class="muted">Upravljanje članovima i produženje članarina</p></div><button class="btn" (click)="newMember()">Novi član</button></div>
<div class="card"><input placeholder="Pretraga po imenu, telefonu, email-u" [(ngModel)]="q" (keyup.enter)="load()"><button class="btn" style="margin-top:10px" (click)="load()">Pretraži</button></div>
<div class="card" *ngIf="editing"><h3>{{form.id?'Izmena člana':'Novi član'}}</h3><div class="form-grid">
 <div><label>Ime</label><input [(ngModel)]="form.firstName"></div><div><label>Prezime</label><input [(ngModel)]="form.lastName"></div><div><label>Status</label><select [(ngModel)]="form.status"><option>ACTIVE</option><option>BLOCKED</option><option>INACTIVE</option></select></div>
 <div><label>Telefon</label><input [(ngModel)]="form.phone"></div><div><label>Email</label><input [(ngModel)]="form.email"></div><div><label>Napomena</label><input [(ngModel)]="form.note"></div>
 </div><div class="actions" style="margin-top:12px"><button class="btn" (click)="save()">Sačuvaj</button><button class="btn secondary" (click)="editing=false">Otkaži</button></div></div>
<div class="card"><table><thead><tr><th>Član</th><th>Telefon</th><th>Email</th><th>Status</th><th>Akcije</th></tr></thead><tbody><tr *ngFor="let m of members"><td>{{m.firstName}} {{m.lastName}}</td><td>{{m.phone}}</td><td>{{m.email}}</td><td><span class="badge" [class.ok]="m.status==='ACTIVE'" [class.bad]="m.status!=='ACTIVE'">{{m.status}}</span></td><td class="actions"><button class="btn secondary" (click)="edit(m)">Izmeni</button><button class="btn" (click)="openSub(m)">Produži</button></td></tr></tbody></table></div>
<div class="card" *ngIf="selected"><h3>Produženje članarine: {{selected.firstName}} {{selected.lastName}}</h3><div class="form-grid"><div><label>Paket</label><select [(ngModel)]="sub.planId"><option *ngFor="let p of plans" [ngValue]="p.id">{{p.name}} - {{p.price}}</option></select></div><div><label>Početak</label><input type="date" [(ngModel)]="sub.startDate"></div><div><label>Cena</label><input type="number" [(ngModel)]="sub.price"></div></div><button class="btn" style="margin-top:12px" (click)="createSub()">Kreiraj članarinu</button><h4>Istorija članarina</h4><table><tr><th>Paket</th><th>Od</th><th>Do</th><th>Cena</th><th>Status</th></tr><tr *ngFor="let s of subs"><td>{{s.planName}}</td><td>{{s.startDate}}</td><td>{{s.endDate}}</td><td>{{s.price}}</td><td>{{s.status}}</td></tr></table></div>
`})
export class MembersComponent implements OnInit{members:Member[]=[];plans:Plan[]=[];subs:Subscription[]=[];q='';editing=false;form:Member={firstName:'',lastName:'',status:'ACTIVE'};selected?:Member;sub:any={};constructor(private api:ApiService){}ngOnInit(){this.load();this.api.plans().subscribe(x=>this.plans=x);}load(){this.api.members(this.q).subscribe(x=>this.members=x);}newMember(){this.editing=true;this.form={firstName:'',lastName:'',status:'ACTIVE'};}edit(m:Member){this.editing=true;this.form={...m};}save(){this.api.saveMember(this.form).subscribe(()=>{this.editing=false;this.load();});}openSub(m:Member){this.selected=m;this.sub={memberId:m.id,planId:this.plans[0]?.id,startDate:new Date().toISOString().substring(0,10),price:this.plans[0]?.price||0};this.api.subscriptions(m.id!).subscribe(x=>this.subs=x);}createSub(){if(!this.selected)return;this.api.createSubscription(this.sub).subscribe(()=>this.openSub(this.selected!));}}
